{
	ScrollBar = {
		lineChar = '|',
		sliderChar = '\127',
		upArrowChar = '\30',
		downArrowChar = '\31',
	},
	Button = {
		--focusIndicator = '\183',
	},
	Checkbox = {
		checkedIndicator = '\4',
		leftMarker = '\124',
		rightMarker = '\124',
	},
	Chooser = {
		leftIndicator = '\17',
		rightIndicator = '\16',
	},
	Grid = {
		focusIndicator = '\183',
		inverseSortIndicator = '\24',
	},
	TitleBar = {
		frameChar = '\140',
		closeInd = '\215',
	},
}
